const FETCH_REQUEST = 'menu/FETCH_REQUEST';
const FETCH_SUCCESS = 'menu/FETCH_SUCCESS';
const FETCH_ERROR = 'menu/FETCH_ERROR';
const CHANGE_FILTER = 'menu/CHANGE_FILTER';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  CHANGE_FILTER,
};
