export const actionTypes = {
  ADD_TO_CART: 'cart/ADD_TO_CART',
  REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
  INCREMENT_AMOUNT: 'cart/INCREMENT_AMOUNT',
  DECREMENT_AMOUNT: 'cart/DECREMENT_AMOUNT',
};
