const FETCH_REQUEST = 'categories/FETCH_REQUEST';
const FETCH_SUCCESS = 'categories/FETCH_SUCCESS';
const FETCH_ERROR = 'categories/FETCH_ERROR';
const CATEGORY = 'category/CATEGORY';
const CLEAR_CATEGORY_SELECTOR = 'category/CLEAR_CATEGORY_SELECTOR';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  CATEGORY,
  CLEAR_CATEGORY_SELECTOR,
  FETCH_ERROR,
};
